[package]
name = "hypervisor"
version = "0.1.0"
edition = "2024"

[dependencies]
arch_x86_64 = { version = "0.1.0", path = "../arch_x86_64" }
goblin = "0.10.4"
kvm-bindings = "0.14.0"
kvm-ioctls = "0.24.0"
nix = "0.30.1"
