[workspace]
members = [
    "arch_x86_64",
    "hypervisor",
    "kernel"
]

resolver = "2"

[profile.kernel-dev]
inherits = "dev"
panic = "abort"
[profile.kernel-release]
inherits = "release"
panic = "abort"
